ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/auth-secret: books-api-prod-basicauthsecret
  hosts:
    - books-gui.k8.wildwidewest.xyz
  secretName: books-gui-prod-secret
  tls:
    - hosts:
        - books-gui.k8.wildwidewest.xyz
      secretName: books-gui-prod-secret