repositories:
  - name: softeamouest-softwarefactory
    url: https://softeamouest-opus.github.io/charts

releases:

  - name: books-api-prod
    namespace: prod
    chart: softeamouest-softwarefactory/books-api
    values:
      - "./values.yaml"
      - image:
          tag: {{ requiredEnv "IMAGE" }}
    secrets:
      - "./secrets.yaml"