repositories:
  - name: softeamouest-softwarefactory
    url: https://softeamouest-opus.github.io/charts

releases:

  - name: books-api-oidc
    namespace: oidc
    chart: softeamouest-softwarefactory/books-api
    values:
      - "./values.yaml"
      - image:
          tag: {{ requiredEnv "IMAGE" }}
        namespace: oidc
        ingress:
          annotations:
            nginx.ingress.kubernetes.io/auth-secret: books-api-oidc-basicauthsecret
          secretName: books-api-oidc-secret
          hosts:
            - books-api-oidc.k8.wildwidewest.xyz
          tls:
            - hosts:
                - books-api-oidc.k8.wildwidewest.xyz
              secretName: books-api-oidc-secret
    secrets:
      - "./secrets.yaml"