repositories:
  - name: softeamouest-softwarefactory
    url: https://softeamouest-opus.github.io/charts

releases:

  - name: books-api-dev
    namespace: dev
    chart: softeamouest-softwarefactory/books-api
    values:
      - "./values.yaml"
      - image:
          tag: {{ requiredEnv "IMAGE" }}
        namespace: dev
        ingress:
          annotations:
            nginx.ingress.kubernetes.io/auth-secret: books-api-{{ .namespace }}-basicauthsecret
          secretName: books-api-{{ .namespace }}-secret
          hosts:
            - books-api-{{ .namespace }}.k8.wildwidewest.xyz
          tls:
            - hosts:
                - books-api-{{ .namespace }}.k8.wildwidewest.xyz
              secretName: books-api-{{ .namespace }}-secret
    secrets:
      - "./secrets.yaml"