repositories:
  - name: softeamouest-softwarefactory
    url: https://softeamouest-opus.github.io/charts

releases:

  - name: books-gui-oidc
    namespace: dev
    chart: softeamouest-softwarefactory/books-gui
    values:
      - "./values.yaml"
      - image:
          tag: {{ requiredEnv "IMAGE" }}
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/auth-secret: books-api-oidc-basicauthsecret
          secretName: books-gui-oidc-secret
          hosts:
            - books-gui-oidc.k8.wildwidewest.xyz
          tls:
            - hosts:
                - books-gui-oidc.k8.wildwidewest.xyz
              secretName: books-gui-oidc-secret