ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/auth-secret: books-api-oidc-basicauthsecret
  hosts:
    - books-gui-oidc.k8.wildwidewest.xyz
  secretName: books-gui-oidc-secret
  tls:
    - hosts:
        - books-gui-oidc.k8.wildwidewest.xyz
      secretName: books-gui-oidc-secret