ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/issuer: letsencrypt-issuer
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - books-gui-dev.k8.wildwidewest.xyz
  secretName: books-gui-dev-secret
  tls:
    - hosts:
        - books-gui-dev.k8.wildwidewest.xyz
      secretName: books-gui-dev-secret